export const idioms = {
  "about to": "almost ready to",
  "above all": "most importantly",
  "add up": "make sense; be logical",
  "all at once": "suddenly; without warning",
  "all of a sudden": "all at once; suddenly",
  "as a matter of fact": "in reality; actually",
  "as a rule": "generally; customarily",
  "at ease": "not nervous; calm",
  "as the drop of a hat": "quickly; without any preparation time",
  "back out(of)": "withdraw an offer",
  "bank on": "depend on; count on",
  "be my guest": "do what you want; feel free; help yourself",
  "be rusty": "need practice or review",
  "beats me": "I don't know; I have no idea (often used in response to a question)",
  "better off": "in an improved condition.",
  "bite off more than one can chew": "take on more responsibility than one can handle",
  "bound to": "certain to; sure to",
  "Break down": "stop functioning (a machine: for example)",
  "break in (on)": "interrupt",
  "break the ice": "break through social barriers (as at a party)",
  "break the news (to)": "inform; give bad news",
  "break up": "end (a meeting for example)",
  "break up (with)": "stop being a couple (a boyfriend and girlfriend, for example)",
  "a breeze": "something very simple and easy to do",
  "bring about": "cause to hapen",
  "bring up": "(1) raise(a child) (2) introduce (a topicm for example)",
  "brush up on": "review; study; practice",
  "bump into": "meet unexpectedly; run into",
  "by and large": "mostly; generally; on the whole",
  "by heart": "by memory; learned word for word",
  "by no means": "in no way; not at all",
  "call it a day": "stop working for the day; go home",
  "call off": "cancel",
  "call on": "visit",
  "calm down": "relax",
  "care for": "(1) take care of (2) like; feel affection for",
  "catch on": "become popular",
  "catch on (to)": "understand; learn",
  "catch up (with)": "go as fast as; catch",
  "check in (or into)": "register(at a hotel)",
  "check out (of)": "(1) leave (a hotel) (2) take material (from a library, for example)",
  "cheer up": "become cheerful; be happy",
  "chip in (on/for)": "contribute",
  "clear up": "(1) clarify; make understandable (2) become nice and sunny(used to talk about the weather)",
  "come across": "find; meet; encounter",
  "come around (to)": "begin to change one's opinion; begin to agree with",
  "come down with": "become sick with (illness)",
  "come up with": "think of (an idea)",
  "cost an arm and a leg": "be very expensive",
  "count on": "depend on; rely on; bank on",
  "count out": "eliminate; no longer consider as a factor",
  "cut off": "stop; descontinue (a service, for example)",
  "cut out for": "have an aptitude for; be qualified for",
  "day in and day out": "constantly; for a long time",
  "die down": "become less severe; quiet down",
  "do over": "do again; repeat",
  "do without": "not have",
  "down the drain": "wasted; done for no reason (work, for example)",
  "dream up": "invent; think of; come up with",
  "drop (someone) a line": "send someone a letter",
  "drop in (on)": "visit informally",
  "drop off": "(1) leave something(a package, for example) (2) take (someone) home; let someone out of a car",
  "drop out (of)": "stop attending(classes, for example)",
  "easy as pie": "very simple; a piece of cake",
  "eyes bigger than one's stomach": "said of someone who takes more food than he or she can eat",
  "fall behind": "not move as quickly as; lag behind",
  "fall through": "fail to happen",
  "a far cry from": "not similar to; not as good as",
  "fed up (with)": "not able to tolerate; disgusted with; annoyed by feel",
  "fell free": "do something if one wants",
  "feel like": "be inclined to; want to",
  "feel like a million dollars": "feel very good",
  "feel up to": "feel able to do something; ready to",
  "few and far between": "uncommon and infrequent",
  "figure out": "understand; solve",
  "fill in": "write in a blank (on an application form, for example)",
  "fill in (for)": "substitute for",
  "fill on": "provide missing information",
  "fill out": "complete (an application form, for example)",
  "find out": "learn; discover",
  "a fish out of water": "someone not in his or her normal surroundings",
  "fix up": "repair; renovate",
  "follow in one's footsteps": "do what someone else did (especially a parent)",
  "for good": "permanently; forever",
  "for the time being": "temporarily; for now",
  "from out of the blue": "unexpectedly; without warning",
  "get a kick out of (doing something)": "enjoy; have fun doing something",
  "get along with": "have good relations with",
  "get carried away": "go too far; do too much; buy too much",
  "get in one's blood": "become a habit; become customary",
  "get in over one's head": "take on too much responsibility; bite off more than one can chew",
  "get in the way": "block; obstruct",
  "get in touch with": "contact",
  "get off": "leave (a vehicle)",
  "get off the ground": "start to be successful",
  "get on": "board (vehicle)",
  "get over": "recover from (a disease)",
  "get rid of": "discard; no longer have",
  "get under way": "begin; start",
  "give (someone) a cold shoulder": "act unfriendly toward someone; ignore",
  "give away": "distribute(for free)",
  "get the hang of something": "learn how to do something",
  "give a hand": "applaud; clap, give a hand (with) assist",
  "go easy on": "not punish severely",
  "go on (with)": "continue",
  "go overboard": "do too much; buy too much",
  "go with": "(1) accompany (2) look good together; complement (for example: two articles of clothing)",
  "go without saying": "be clear; be obvious",
  "grow up": "to mature; to become an adult",
  "hand in": "give back to; return",
  "hand out": "distribute",
  "hang on": "wait",
  "hard to come by": "difficult to find",
  "have a heart": "be compassionate; show mercy",
  "have a hunch": "have an intuitive feeling",
  "have a word with (someone)": "talk to someone briefly",
  "have on": "wear",
  "have one's hands full": "be very busy; have a challenging job",
  "have the time of one's life": "have fun; have a great time",
  "hear fIrsthand (from)": "get information directly from someone",
  "hear from": "be contacted by; be in touch with",
  "hear of": "know about; be familiar with",
  "hit it off": "become friendly (especially at a first meeting)",
  "hit the road": "leave; go away",
  "hold on": "wait",
  "hold on (to)": "grasp",
  "hold still": "not move",
  "hold up": "delay",
  "in a nutshell": "in summary; in brief",
  "in favor of": "in agreement with; supporting",
  "in hot water": "in trouble",
  "in no time": "very soon; very quickly",
  "in person": "face to face (not by telephone, letter, etc.)",
  "in store": "in the future; coming up",
  "in the dark": "not knowing; confused",
  "in the long run": "over a long period of time",
  "in the same boat": "in the same situation; having the same problem",
  "iron out": "solve(a problem)",
  "join the club": "have the same problem as other people",
  "jump to conclusions": "form opinions without sufficient evidence",
  "keep an eye on": "watch; take care of; look after",
  "keep an eye out (for)": "look for",
  "keep on (with)": "continue",
  "keep track of": "know where something or someone is",
  "keep up (with)": "maintain the same speed as",
  "kill time": "spend time doing unimportant things (before an appointment, for example)",
  "know like the back of one's hand": "be very familiar with",
  "lay off": "put out of work",
  "learn the ropes": "become familiar with; get used to; get the hang of",
  "leave out": "not include; omit",
  "leave someone / something alone": "not disturb",
  "let someone down": "disappoint",
  "let up": "decline in intensity (rain for example)",
  "look after": "take care of; mind",
  "look for": "try to locate",
  "look forward to": "antecipate (with pleasure)",
  "look into": "investigate",
  "look like": "resemble",
  "look out(for)": "be careful",
  "look over": "examine; read",
  "look up": "(1) find information (especially in a reference book) (2) try to locate someone",
  "look up to": "respect; admire",
  "make a fool of oneself": "act embarrassingly",
  "make a point of": "make a special effort",
  "make ends meet": "balance a budget",
  "make sense (of)": "be logical and clear; understand",
  "make up": "invent; create",
  "make up one's mind": "decide",
  "make way for": "allow space for; provide a path for",
  "mean to": "intend to",
  "mixed up": "confused",
  "music to one's ears": "something that sounds pleasant",
  "a nervous wreck": "someone who is very nervous",
  "next to nothing": "very little (money, for example); cheap",
  "no doubt about it": "certainly; definitely",
  "no harm done": "there was no damage done",
  "not at all": "not in any way; not to any degree",
  "not believe one's ears (or eyes)": "be unable to believe what one hears (or sees)",
  "not think much of": "not like; not have a good opinion of",
  "odds and ends": "small; miscellaneous items",
  "an old hand(at)": "an experienced person",
  "on edge": "nervous",
  "on end": "consecutively; without a break (days on end, for example)",
  "on hand": "easily available",
  "on needles and pins": "nervous; ansious",
  "on one's own": "independent",
  "on second thought": "after reconsidering",
  "on the go": "always busy; always moving",
  "on the tip of one's tongue": "almost able to remember",
  "on the whole": "in general",
  "out of (something)": "not having something",
  "out of one's mind": "insane; illogical; irrational",
  "out of order": "broken; not functioning properly",
  "out of the question": "definitely not; impossible",
  "over and over": "again and again; repeatedly",
  "over one's head": "not understandable (a joke, for example); obscure",
  "part with": "no longer have; et rid of; not be in the company of",
  "pass up": "not accept; not choose",
  "pass with flying colors": "do very well (on a test) ",
  "pat oneself on the back": "congratulate oneself",
  "pay attention (to)": "concentrate on; focus on",
  "pick out": "choose; select",
  "pick up": "(1) take something from a surface (for example: a floor) (2) go to a location and get someone or something (3) learn (especially without formal training)",
  "pick up the tab(for)": "pay for",
  "the picture of": "a perfect example of something",
  "play it by ear": "do something without a definite plan",
  "play it safe": "choose a cautious plan",
  "point out": "indicate",
  "a pretty penny": "a lot of money",
  "pull one's leg": "joke with someone; make up a story",
  "push one's luck": "to continue doing something too long; to keep taking chances",
  "put aside": "save for later; set aside",
  "put away": "return something to its proper place",
  "put off": "delay; postpone",
  "put on": "begin to wear",
  "put together": "assemble",
  "put up with": "tolerate",
  "right away": "immediately",
  "ring a bell (with)": "sound familiar to",
  "rough it": "experience somewhat difficult or primitive conditions",
  "rule out": "say something is impossible; eliminate",
  "run a temperature": "have a fever",
  "run for office": "try to get elected",
  "run into": "(1) meet unexpectedly; bump into (2) collide with",
  "run late": "be late; be in a hurry",
  "run of the mill": "ordinary",
  "run out of": "exhaust the supply of",
  "save one's breath": "don't bother asking someone",
  "search me": "I don't know; I have no idea; beats me",
  "see eye to eye (with someone) (on something)": "have the same opinion; be in agreement",
  "see (someone) off": "accompany (to an airport or train station, for example)",
  "see to": "take care of; check on; fix",
  "serve one right": "receive the proper punishment; get the penalty one deserves",
  "short for": "a nickname for",
  "show around": "orient; give a tour",
  "show off": "try to attract attention by unusual behavior",
  "show up": "arrive",
  "shut down": "close",
  "sign up (for)": "enrol l(for a class, for example)",
  "sing another tune": "change one's opinion; feel differently",
  "size up": "measure; estimate",
  "sleep on it": "postpone a decision until the next day",
  "slowly but surely": "gradually; steadily but not quickly",
  "snowed under": "very busy",
  "so far so good": "up until now: there are no problems",
  "sooner or later": "at some indefinite future time",
  "speak one's mind": "say what one is thinking",
  "speak up": "speak more loudly",
  "speak up for": "support verbally",
  "spell out (for)": "make something very clear; explain in detail",
  "spick and span": "extremely clean; spotless",
  "stack up against": "compare with",
  "stamp out": "eliminate; wipe out",
  "stand for": "(1) tolerate; put up with (2) symbolize represent",
  "stand out": "be noticeable",
  "stay out": "not come home",
  "stay out (or up) to all hours": "come home (or go to bed) very late",
  "stay up": "not go to bed",
  "stick with": "not change; stay with",
  "stock up on": "get a large supply of something",
  "a stone's throw from": "not far away from; close to",
  "stop by": "visit informally; go to see",
  "straighten up": "clean up; make tidy",
  "stuck with": "have something one cannot get rid of",
  "take a break": "stop working for a short time",
  "take a lot of nerve": "require a lot of courage",
  "take a lot out of (someone)": "be hard on someone; drain energy from someone",
  "take advantage of": "utilize; make use of; exploit",
  "take after": "resemble; look like (especially an older relative)",
  "take apart": "disassemble",
  "take it easy": "relax; calm down",
  "take a short cut": "take a more direct or faster route than usual",
  "take off": "(1) remove (clothing, for example) (2) ascend (a plane, for example) (3) hecome popular quickly",
  "take over": "assume control or responsibility",
  "take part (in)": "participate in",
  "take the plunge": "finally take action; do something different",
  "take time off (from)": "take a vacation or a break from work or school",
  "take up": "begin to study some topic or engage in some activity",
  "talk down to": "speak to someone as if he or she were a child; patronize",
  "talk into": "persuade; convince",
  "talk out of": "dissuade; convince not to do something",
  "talk over": "discuss",
  "tear oneself away from something": "stop doing something interesting",
  "tear up": "rip into small pieces",
  "tell apart": "distinguish",
  "things are looking up": "the situation is improving",
  "think over": "consider",
  "throw away": "discard; get rid of",
  "throw cold water on": "discourage; force to cancel (a plan, for example)",
  "throw the book at someone": "give someone the maximum punishment",
  "try on": "test clothing before buying (for size, style, and so on)",
  "try out": "test a product before buying",
  "try out (for)": "audition for (a role in a play, for example); attempt to join (a team, for example)",
  "turn around": "face in a different direction",
  "turn down": "(1) reject an offer (2) decrease the intensity of",
  "turn in": "(1) return; give back; hand in (2) go to bed",
  "turn into": "change to; transform into",
  "turn off": "stop the operation (of an appliance, for example); shut off",
  "turn on": "start the operation (of an appliance, for example)",
  "turn out": "(1) result; end up; be the final product (2) produce (3) arrive; gather(for a meeting, for example)",
  "turn up": "(1) increase in intensity(2) arrive",
  "under the weather": "slightly ill",
  "use up": "usc completely",
  "wait on": "serve",
  "walk on air": "be very happy",
  "warm up": "(1) heat (2) practice; prepare for",
  "warm up (to)": "become friendly with; start to enjoy",
  "watch out (for)": "be alert; look out for",
  "wear out": "become no longer useful because of wear",
  "what the doctor ordered": "exactly what was needed; the perfect thing",
  "wipe out": "eliminate; stamp out",
  "without": "without a problem",
  "work out": "(1) exercise (2) bring to a successful conclusion; solve"
};
